require('dotenv').config();
const express=require('express'),session=require('express-session'),bcrypt=require('bcryptjs'),Database=require('better-sqlite3'),crypto=require('crypto'),path=require('path');
const app=express(),PORT=Number(process.env.PORT||3000),db=new Database('licenses.db');
db.pragma('journal_mode=WAL');db.exec(`CREATE TABLE IF NOT EXISTS licenses(id INTEGER PRIMARY KEY AUTOINCREMENT,key TEXT UNIQUE NOT NULL,status TEXT NOT NULL DEFAULT 'active',expires_at TEXT,hwid TEXT,note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT NOT NULL,license_id INTEGER,key TEXT,detail TEXT NOT NULL DEFAULT '',ip TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);`);
app.use(express.json({limit:'64kb'}));app.use(express.urlencoded({extended:false}));app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',maxAge:8*60*60*1000}}));app.use(express.static(path.join(__dirname,'public')));
const now=()=>new Date().toISOString(),ip=req=>String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim();
function makeKey(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',p=()=>Array.from({length:5},()=>a[crypto.randomInt(0,a.length)]).join('');return `${p()}-${p()}-${p()}-${p()}`}
function audit(req,action,row,detail=''){db.prepare('INSERT INTO audit_logs(action,license_id,key,detail,ip,created_at) VALUES(?,?,?,?,?,?)').run(action,row?.id||null,row?.key||null,detail,ip(req),now())}
const auth=(req,res,next)=>req.session.admin?next():res.status(401).json({error:'Unauthorized'}), admin=()=>process.env.ADMIN_USERNAME||'admin';
app.get('/api/health',(req,res)=>res.json({ok:true,time:now()}));
app.post('/api/admin/login',async(req,res)=>{const u=String(req.body.username||''),p=String(req.body.password||'');if(u!==admin()||!(await bcrypt.compare(p,bcrypt.hashSync(process.env.ADMIN_PASSWORD||'change-me',10))))return res.status(401).json({error:'Sai tài khoản hoặc mật khẩu'});req.session.admin=true;res.json({ok:true,username:u})});
app.post('/api/admin/logout',auth,(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get('/api/admin/me',auth,(req,res)=>res.json({ok:true,username:admin()}));
app.get('/api/admin/stats',auth,(req,res)=>{const t=now();res.json({total:db.prepare('SELECT COUNT(*) c FROM licenses').get().c,active:db.prepare("SELECT COUNT(*) c FROM licenses WHERE status='active' AND (expires_at IS NULL OR expires_at>?)").get(t).c,banned:db.prepare("SELECT COUNT(*) c FROM licenses WHERE status='banned'").get().c,bound:db.prepare("SELECT COUNT(*) c FROM licenses WHERE hwid IS NOT NULL AND hwid!=''").get().c})});
app.get('/api/admin/licenses',auth,(req,res)=>{let sql='SELECT * FROM licenses WHERE 1=1',a=[],q=String(req.query.q||'').trim(),s=String(req.query.status||'all');if(q){sql+=' AND(key LIKE ? OR hwid LIKE ? OR note LIKE ?)';let x=`%${q}%`;a.push(x,x,x)}if(['active','banned','disabled'].includes(s)){sql+=' AND status=?';a.push(s)}res.json(db.prepare(sql+' ORDER BY id DESC LIMIT 1000').all(...a))});
function create(req,d,n){let k;do{k=makeKey()}while(db.prepare('SELECT 1 FROM licenses WHERE key=?').get(k));let e=d>0?new Date(Date.now()+d*86400000).toISOString():null,info=db.prepare('INSERT INTO licenses(key,status,expires_at,note,created_at) VALUES(? ,\'active\',?,?,?)').run(k,e,n,now()),r=db.prepare('SELECT * FROM licenses WHERE id=?').get(info.lastInsertRowid);audit(req,'create',r,`duration_days=${d}`);return r}
app.post('/api/admin/licenses',auth,(req,res)=>res.json({license:create(req,Math.max(0,Math.min(36500,Number(req.body.duration_days||0))),String(req.body.note||'').slice(0,500))}));
app.post('/api/admin/licenses/bulk',auth,(req,res)=>{let c=Math.max(1,Math.min(500,Number(req.body.count||1))),d=Math.max(0,Math.min(36500,Number(req.body.duration_days||0))),n=String(req.body.note||'').slice(0,500);let f=db.transaction(()=>Array.from({length:c},()=>create(req,d,n)));res.json({licenses:f()})});
app.patch('/api/admin/licenses/:id',auth,(req,res)=>{let r=db.prepare('SELECT * FROM licenses WHERE id=?').get(req.params.id),s=String(req.body.status||'');if(!r)return res.status(404).json({error:'Không tìm thấy key'});if(!['active','banned','disabled'].includes(s))return res.status(400).json({error:'Trạng thái không hợp lệ'});db.prepare('UPDATE licenses SET status=? WHERE id=?').run(s,r.id);r=db.prepare('SELECT * FROM licenses WHERE id=?').get(r.id);audit(req,'status_'+s,r);res.json({license:r})});
app.post('/api/admin/licenses/:id/reset-hwid',auth,(req,res)=>{let r=db.prepare('SELECT * FROM licenses WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({error:'Không tìm thấy key'});db.prepare('UPDATE licenses SET hwid=NULL WHERE id=?').run(r.id);audit(req,'reset_hwid',r);res.json({ok:true})});
app.delete('/api/admin/licenses/:id',auth,(req,res)=>{let r=db.prepare('SELECT * FROM licenses WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({error:'Không tìm thấy key'});db.prepare('DELETE FROM licenses WHERE id=?').run(r.id);audit(req,'delete',r);res.json({ok:true})});
app.get('/api/admin/logs',auth,(req,res)=>res.json(db.prepare('SELECT * FROM audit_logs ORDER BY id DESC LIMIT 500').all()));
function validate(req,res,action){let k=String(req.body.key||'').trim().toUpperCase(),h=String(req.body.hwid||'').trim(),r=db.prepare('SELECT * FROM licenses WHERE key=?').get(k);if(!k||!h)return res.status(400).json({ok:false,error:'Thiếu key hoặc HWID'});if(!r)return res.status(404).json({ok:false,error:'Key không tồn tại'});if(r.status!=='active')return res.status(403).json({ok:false,error:r.status==='banned'?'Key đã bị khóa':'Key đã bị vô hiệu hóa'});if(r.expires_at&&new Date(r.expires_at)<=new Date())return res.status(403).json({ok:false,error:'Key đã hết hạn'});if(r.hwid&&r.hwid!==h)return res.status(403).json({ok:false,error:'Key đã được liên kết với thiết bị khác'});if(!r.hwid){db.prepare('UPDATE licenses SET hwid=? WHERE id=?').run(h,r.id);r.hwid=h;audit(req,'hwid_bound',r)}audit(req,action,r);res.json({ok:true,key:r.key,status:r.status,expires_at:r.expires_at,hwid_bound:true})}
app.post('/api/license/activate',(q,r)=>validate(q,r,'activate'));app.post('/api/license/validate',(q,r)=>validate(q,r,'validate'));app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log(`AnhVuong License Server running on port ${PORT}`));
